version: "3.8"
services:
  frontend_container:
    build: ./frontend
    ports: 
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend_container:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    volumes:
      - ./backend/facebook_clone:/code/facebook_clone

  postgres_db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=facebook_clone
    ports:
      - '5432:5432'
    volumes:
        - db_data:/var/lib/postgresql/data/

volumes:
    db_data:
